### PR TITLE
Multiple folder structure added

### PR DESCRIPTION
**Pull request by rohitrango**
screenshot from 2016-04-23 12 23 32

### CODE REVIEW

**Comment by CodeMaxx** [comment]
We have intentionally not kept such structure. It is very messy. Also deleting `Cred.txt` creates no problem at all, its already being handled.

**Comment by rohitrango** [comment]
What kind of structure does this project require then ? I actually want to work on this script, so tell me any way I could help :)

**Comment by rohitrango** [comment]
And yes, Cred.txt does create problems in some cases (I tested them myself) so I added the extra line

**Comment by CodeMaxx** [comment]
At present no changes in structure are required. Currently we are not accepting any contributions except those from the Collaborators. We will be releasing this next semester. You can start contributing then. Any suggestions are always welcome. Thanx for the offer 😄 

We'll look into the `Cred.txt` problem 👍

**Comment by rohitrango** [comment]
And who are the collaborators ? Everyone except me ?

**Comment by CodeMaxx** [comment]
@nihal111 @arpan98 and me. Nobody else.

**Comment by arpan98** [comment]
@rohitrango The directory structure that is currently there is just fine and will not be changed. Please open a seperate issue for the `Cred.txt` problem you have faced with details.

**Comment by rohitrango** [comment]
@arpan98 im not supposed to contribute to this project as per @CodeMaxx  until next semester. :+1:

**Comment by CodeMaxx** [comment]
Some people

**Pull request closed without merging**
